<?php

namespace App\Console\Commands;

use App\Services\PersistentStorage;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;
use RuntimeException;
use Throwable;

class CleanupLocalPersistentStorage extends Command
{
    protected $signature = 'persistent-storage:cleanup-local
        {manifest : Manifest JSONL path generated by persistent-storage:migrate-s3}
        {--execute : Delete matching local files. Without it, only report planned cleanup}
        {--limit=0 : Maximum manifest rows to inspect}';

    protected $description = 'Delete local persistent files after S3 migration manifest verification';

    /** @var array<string, int> */
    private array $counts = [
        'inspected' => 0,
        'planned' => 0,
        'deleted' => 0,
        'missing_local' => 0,
        'mismatch' => 0,
        'out_of_scope' => 0,
        'failed' => 0,
    ];

    public function handle(): int
    {
        if (!PersistentStorage::usesS3()) {
            $this->error('FILE_STORAGE_DISK must be set to s3 before local persistent files can be cleaned.');
            return self::FAILURE;
        }

        $manifestPath = $this->manifestPath();
        if (!is_file($manifestPath) || !is_readable($manifestPath)) {
            $this->error("Manifest is not readable: {$manifestPath}");
            return self::FAILURE;
        }

        $execute = (bool) $this->option('execute');
        $limit = max(0, (int) $this->option('limit'));
        if (!$execute) {
            $this->warn('Dry run: no local file will be deleted. Use --execute to cleanup.');
        }

        $handle = fopen($manifestPath, 'rb');
        if ($handle === false) {
            $this->error("Unable to open manifest: {$manifestPath}");
            return self::FAILURE;
        }

        try {
            while (($line = fgets($handle)) !== false) {
                if ($limit > 0 && $this->counts['inspected'] >= $limit) {
                    break;
                }
                $this->counts['inspected']++;
                $this->cleanupLine(trim($line), $execute);
            }
        } finally {
            fclose($handle);
        }

        $this->newLine();
        $this->table(['Result', 'Count'], collect($this->counts)
            ->map(fn (int $count, string $name) => [$name, $count])
            ->values()
            ->all());

        if ($this->counts['failed'] > 0 || $this->counts['mismatch'] > 0) {
            $this->error('Cleanup completed with failures or mismatches. Resolve them before retrying.');
            return self::FAILURE;
        }

        return self::SUCCESS;
    }

    private function cleanupLine(string $line, bool $execute): void
    {
        if ($line === '') {
            return;
        }

        try {
            $row = json_decode($line, true, 512, JSON_THROW_ON_ERROR);
            $key = ltrim(str_replace('\\', '/', (string) ($row['key'] ?? '')), '/');
            if (!PersistentStorage::isPersistentKey($key)) {
                $this->counts['out_of_scope']++;
                return;
            }

            $localPath = public_path($key);
            if (!is_file($localPath)) {
                $this->counts['missing_local']++;
                return;
            }

            $size = filesize($localPath);
            $hash = hash_file('sha256', $localPath);
            if ($size === false || $hash === false || (int) ($row['size'] ?? -1) !== (int) $size || !hash_equals((string) ($row['sha256'] ?? ''), $hash)) {
                $this->counts['mismatch']++;
                $this->warn("Local mismatch, skipped: {$key}");
                return;
            }

            $remote = $this->remoteChecksum($key);
            if ($remote['size'] !== (int) $size || !hash_equals($hash, $remote['hash'])) {
                $this->counts['mismatch']++;
                $this->warn("S3 mismatch, skipped: {$key}");
                return;
            }

            $this->counts['planned']++;
            if (!$execute) {
                $this->line($key);
                return;
            }

            if (!@unlink($localPath)) {
                throw new RuntimeException("Unable to delete local file: {$key}");
            }
            $this->removeEmptyDirectories(dirname($localPath));
            $this->counts['deleted']++;
        } catch (Throwable $exception) {
            $this->counts['failed']++;
            $this->error($exception->getMessage());
        }
    }

    private function manifestPath(): string
    {
        $path = trim((string) $this->argument('manifest'));
        return str_starts_with($path, DIRECTORY_SEPARATOR) ? $path : base_path($path);
    }

    private function removeEmptyDirectories(string $directory): void
    {
        $uploadsRoot = rtrim(public_path('uploads'), DIRECTORY_SEPARATOR);
        while (str_starts_with($directory, $uploadsRoot) && $directory !== $uploadsRoot && is_dir($directory)) {
            $items = scandir($directory);
            if ($items === false || array_diff($items, ['.', '..']) !== []) {
                return;
            }
            @rmdir($directory);
            $directory = dirname($directory);
        }
    }

    /** @return array{size: int, hash: string} */
    private function remoteChecksum(string $key): array
    {
        $stream = Storage::disk('s3')->readStream($key);
        if (!is_resource($stream)) {
            throw new RuntimeException("Unable to read S3 object: {$key}");
        }

        $hash = hash_init('sha256');
        $size = 0;
        try {
            while (!feof($stream)) {
                $chunk = fread($stream, 1024 * 1024);
                if ($chunk === false) {
                    throw new RuntimeException("Unable to read S3 object: {$key}");
                }
                $size += strlen($chunk);
                hash_update($hash, $chunk);
            }
        } finally {
            fclose($stream);
        }

        return ['size' => $size, 'hash' => hash_final($hash)];
    }
}
